using System.Diagnostics;
using System.Text;

namespace BHServe.Core;

/// <summary>
/// Optional Apache backend (for sites that need native .htaccess). nginx stays the
/// front (TLS + :80/:443) and proxies the host to Apache on 127.0.0.1:8080, which
/// serves with AllowOverride All and hands .php to php-cgi via mod_proxy_fcgi.
/// Windows-specific vs the mac engine: the winnt MPM, module paths under the build's
/// <c>modules\</c>, no User/Group/unixd, and forward-slash paths.
/// </summary>
public static class Apache
{
    public const int Port = 8080;
    private static string Dir => Path.Combine(Paths.Home, "apache");
    private static string Conf => Path.Combine(Dir, "httpd.conf");
    private static string SitesDir => Path.Combine(Dir, "sites");
    private static string PidFile => Path.Combine(Paths.Run, "httpd.pid");

    public static bool Available => Tools.HttpdExe() is not null;

    public static bool Running()
    {
        try
        {
            using var c = new System.Net.Sockets.TcpClient();
            return c.ConnectAsync("127.0.0.1", Port).Wait(500) && c.Connected;
        }
        catch { return false; }
    }

    private static string Fwd(string p) => p.Replace('\\', '/');

    public static void RenderMain()
    {
        var root = Tools.ApacheRoot() ?? throw new BhException("Apache not installed");
        var mods = Fwd(Path.Combine(root, "modules"));
        var home = Fwd(Paths.Home);
        Directory.CreateDirectory(SitesDir);
        var sb = new StringBuilder();
        sb.Append($$"""
        # Generated by BHServe (Windows) — Apache backend behind nginx. Do not edit by hand.
        ServerRoot "{{Fwd(root)}}"
        Listen 127.0.0.1:{{Port}}
        # (the winnt MPM is compiled into httpd.exe on Windows — no LoadModule needed)
        LoadModule authz_core_module {{mods}}/mod_authz_core.so
        LoadModule dir_module {{mods}}/mod_dir.so
        LoadModule mime_module {{mods}}/mod_mime.so
        LoadModule rewrite_module {{mods}}/mod_rewrite.so
        LoadModule headers_module {{mods}}/mod_headers.so
        LoadModule setenvif_module {{mods}}/mod_setenvif.so
        LoadModule log_config_module {{mods}}/mod_log_config.so
        LoadModule env_module {{mods}}/mod_env.so
        LoadModule alias_module {{mods}}/mod_alias.so
        LoadModule cgi_module {{mods}}/mod_cgi.so
        LoadModule actions_module {{mods}}/mod_actions.so
        ServerName localhost
        PidFile "{{home}}/run/httpd.pid"
        DefaultRuntimeDir "{{home}}/run"
        TypesConfig "{{Fwd(root)}}/conf/mime.types"
        DirectoryIndex index.php index.html index.htm
        ErrorLog "{{home}}/logs/apache-error.log"
        LogLevel warn
        LimitRequestBody 0
        <Directory />
            AllowOverride none
            Require all denied
        </Directory>
        # Catch-all default vhost — MUST be the FIRST vhost so Apache uses it for any Host that
        # matches no real site. Apache's default for an unmatched Host is its first-listed vhost;
        # without this, a site momentarily missing during a server switch (nginx↔apache) would leak
        # the first real site's page (a user saw another shop's content for ~1s). Now that window
        # returns a clean 404 instead. (Loaded before the site includes below.)
        <VirtualHost 127.0.0.1:{{Port}}>
            ServerName bhserve-default.invalid
            <Location "/">
                Require all denied
                ErrorDocument 403 "<!doctype html><meta charset='utf-8'><title>BHServe</title><p style='font:15px sans-serif;margin:3em'>This site is switching web servers - refresh in a moment.</p>"
            </Location>
        </VirtualHost>
        IncludeOptional "{{home}}/apache/sites/*.conf"

        """);
        Directory.CreateDirectory(Path.GetDirectoryName(Conf)!);
        File.WriteAllText(Conf, sb.ToString());
    }

    /// <summary>Per-site Apache vhost: serves <paramref name="root"/> with .htaccess; .php runs
    /// via mod_cgi + Action (Apache spawns php-cgi.exe per request — the reliable Windows path;
    /// mod_proxy_fcgi over TCP corrupts SCRIPT_FILENAME with the C:\ drive letter).</summary>
    public static void RenderVhost(string name, string domain, string root, string phpKey, Config cfg)
    {
        var version = Services.PhpVersion(phpKey, cfg);
        var phpExe = Tools.PhpCgiExe(version);
        var phpDir = phpExe is not null ? Fwd(Path.GetDirectoryName(phpExe)!) : "";
        var home = Fwd(Paths.Home);
        Directory.CreateDirectory(SitesDir);
        var body = $$"""
        # BHServe Apache backend: {{name}} ({{domain}}) php={{phpKey}}
        <VirtualHost 127.0.0.1:{{Port}}>
            ServerName {{domain}}
            DocumentRoot "{{Fwd(root)}}"
            # TLS terminates at nginx; nginx proxies to us over plain HTTP with X-Forwarded-Proto.
            # Mark https-proxied requests so php-cgi sees $_SERVER['HTTPS']=on — without this,
            # https-enforcing apps (WHMCS/Blesta/WordPress/FOSSBilling) never see https and 302
            # to https forever → ERR_TOO_MANY_REDIRECTS (parity #10; macOS fix v1.7.15).
            SetEnvIf X-Forwarded-Proto "https" HTTPS=on
            <Directory "{{Fwd(root)}}">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>
            ScriptAlias "/__bhphp/" "{{phpDir}}/"
            <Directory "{{phpDir}}">
                Require all granted
                Options +ExecCGI
            </Directory>
            Action application/x-httpd-php "/__bhphp/php-cgi.exe"
            AddType application/x-httpd-php .php
            ErrorLog "{{home}}/logs/{{name}}-apache-error.log"
        </VirtualHost>

        """;
        File.WriteAllText(Path.Combine(SitesDir, $"{name}.conf"), body);
    }

    public static void RemoveVhost(string name)
    {
        try { File.Delete(Path.Combine(SitesDir, $"{name}.conf")); } catch { }
    }

    /// <summary>Validate the config (httpd -t -f conf). Returns (ok, output).</summary>
    private static (bool ok, string output) Test()
    {
        var exe = Tools.HttpdExe()!;
        var psi = new ProcessStartInfo
        {
            FileName = exe, Arguments = $"-t -f \"{Fwd(Conf)}\"",
            UseShellExecute = false, CreateNoWindow = true,
            RedirectStandardOutput = true, RedirectStandardError = true,
            WorkingDirectory = Path.GetDirectoryName(exe)!,
        };
        var p = Process.Start(psi)!;
        var outp = p.StandardOutput.ReadToEnd() + p.StandardError.ReadToEnd();
        p.WaitForExit();
        return (outp.Contains("Syntax OK"), outp);
    }

    /// <summary>Heal Apache vhosts written before the HTTPS=on marker (parity #10): re-render any
    /// conf missing SetEnvIf X-Forwarded-Proto, reconstructing the args from the conf itself. Without
    /// the marker, an https-enforcing app behind the Apache backend redirect-loops. Runs on Start so
    /// existing installs self-heal on the next launch, no user action.</summary>
    private static void HealVhosts()
    {
        try
        {
            if (!Directory.Exists(SitesDir)) return;
            foreach (var f in Directory.EnumerateFiles(SitesDir, "*.conf"))
            {
                var text = File.ReadAllText(f);
                if (text.Contains("X-Forwarded-Proto")) continue;
                var name   = Path.GetFileNameWithoutExtension(f);
                var domain = System.Text.RegularExpressions.Regex.Match(text, @"(?im)^\s*ServerName\s+(\S+)").Groups[1].Value;
                var root   = System.Text.RegularExpressions.Regex.Match(text, @"(?im)^\s*DocumentRoot\s+""([^""]+)""").Groups[1].Value;
                var php    = System.Text.RegularExpressions.Regex.Match(text, @"php=(\S+)").Groups[1].Value;
                if (domain.Length > 0 && root.Length > 0 && php.Length > 0)
                    try { RenderVhost(name, domain, root, php, Config.Load()); } catch { }
            }
        }
        catch { }
    }

    public static (bool ok, string msg) Start()
    {
        var exe = Tools.HttpdExe();
        if (exe is null) return (false, "Apache not installed (no httpd.exe)");
        RenderMain();
        HealVhosts();   // add the HTTPS=on marker to any pre-#10 vhost (parity #10)
        if (Running()) return (true, "apache already running");

        var (tok, tmsg) = Test();
        if (!tok) return (false, "apache config test failed:\n" + tmsg);

        // Run httpd directly (NOT -k start, which controls a Windows service). Detach
        // like nginx: redirect streams so it doesn't hold the caller's console.
        var psi = new ProcessStartInfo
        {
            FileName = exe, Arguments = $"-f \"{Fwd(Conf)}\"",
            UseShellExecute = false, CreateNoWindow = true,
            RedirectStandardOutput = true, RedirectStandardError = true,
            WorkingDirectory = Path.GetDirectoryName(exe)!,
        };
        Process.Start(psi);
        for (var i = 0; i < 12 && !Running(); i++) System.Threading.Thread.Sleep(300);
        return Running() ? (true, $"apache started (:{Port})") : (false, "apache failed to start (see logs\\apache-error.log)");
    }

    public static void Stop()
    {
        try
        {
            if (File.Exists(PidFile) && int.TryParse(File.ReadAllText(PidFile).Trim(), out var pid))
                Process.GetProcessById(pid).Kill(true);
        }
        catch { }
        try { File.Delete(PidFile); } catch { }
    }

    public static void Reload()
    {
        if (Tools.HttpdExe() is null || !Running()) return;
        Stop();
        System.Threading.Thread.Sleep(300);
        Start();
    }
}
