using System.Text;

namespace BHServe.Core;

/// <summary>
/// Renders nginx config for Windows — the analog of the mac engine's
/// <c>render_nginx_main</c> / <c>render_nginx_php_vhost</c>. Two key Windows changes:
/// (1) <c>fastcgi_pass 127.0.0.1:&lt;port&gt;</c> instead of a unix socket, and
/// (2) every path is emitted with forward slashes (nginx on Windows rejects
/// back-slashes in directives).
/// </summary>
public static class NginxConfig
{
    /// <summary>nginx wants forward slashes even on Windows.</summary>
    public static string Fwd(string p) => p.Replace('\\', '/');

    private static string Prefix => Tools.NginxPrefix() ?? Path.Combine(Paths.Bin, "nginx");
    private static string MimeTypes     => Fwd(Path.Combine(Prefix, "conf", "mime.types"));
    private static string FastcgiParams => Fwd(Path.Combine(Prefix, "conf", "fastcgi_params"));

    public static void RenderMain(Config cfg)
    {
        var home = Fwd(Paths.Home);
        var conf = Path.Combine(Paths.Home, "nginx", "nginx.conf");
        var sb = new StringBuilder();
        sb.Append($$"""
        # Generated by BHServe (Windows) — do not edit by hand (regenerated on init / site changes).
        # No `user` directive: Windows nginx ignores it. PHP runs as php-cgi.exe over TCP.
        worker_processes auto;
        error_log {{home}}/logs/nginx-error.log;
        pid {{home}}/run/nginx.pid;
        events {
            worker_connections 4096;
        }
        http {
            include {{MimeTypes}};
            default_type application/octet-stream;
            access_log {{home}}/logs/nginx-access.log;
            client_body_temp_path {{home}}/tmp/client_body;
            proxy_temp_path       {{home}}/tmp/proxy;
            fastcgi_temp_path     {{home}}/tmp/fastcgi;
            uwsgi_temp_path       {{home}}/tmp/uwsgi;
            scgi_temp_path        {{home}}/tmp/scgi;

            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 4096;
            server_names_hash_bucket_size 128;
            server_tokens off;
            client_max_body_size 2048m;

            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_busy_buffers_size 64k;
            fastcgi_read_timeout 600;
            fastcgi_connect_timeout 60;

            gzip on;
            gzip_comp_level 5;
            gzip_min_length 256;
            gzip_proxied any;
            gzip_vary on;
            gzip_types text/plain text/css text/xml text/javascript application/json
                       application/javascript application/xml application/xml+rss
                       application/rss+xml image/svg+xml application/wasm font/ttf font/otf;

            # Catch-all default so an unknown host doesn't leak the first site.
            server {
                listen 127.0.0.1:{{cfg.HttpPort}} default_server;
                server_name _;
                return 444;
            }

            include {{home}}/nginx/sites/*.conf;
        }

        """);
        Directory.CreateDirectory(Path.GetDirectoryName(conf)!);
        File.WriteAllText(conf, sb.ToString());
    }

    /// <summary>Emit the listen/ssl lines for a domain (HTTP always; HTTPS if a cert exists).</summary>
    private static string ListenBlock(string domain, Config cfg)
    {
        var cert = Path.Combine(Paths.Certs, $"{domain}.pem");
        var key  = Path.Combine(Paths.Certs, $"{domain}-key.pem");
        var sb = new StringBuilder();
        sb.AppendLine($"    listen 127.0.0.1:{cfg.HttpPort};");
        if (File.Exists(cert) && File.Exists(key))
        {
            sb.AppendLine($"    listen 127.0.0.1:{cfg.HttpsPort} ssl;");
            sb.AppendLine($"    ssl_certificate {Fwd(cert)};");
            sb.AppendLine($"    ssl_certificate_key {Fwd(key)};");
        }
        else
        {
            sb.AppendLine($"    # HTTPS not provisioned — run: bhserve secure {domain}");
        }
        return sb.ToString().TrimEnd('\r', '\n');
    }

    /// <summary>nginx serves PHP directly via php-cgi over TCP (render_nginx_php_vhost analog).</summary>
    public static void RenderPhpVhost(string name, string domain, string root, string phpKey, Config cfg)
    {
        var version = Services.PhpVersion(phpKey, cfg);
        var port = PhpCgi.PortFor(version);
        var home = Fwd(Paths.Home);
        var conf = Path.Combine(Paths.NginxSites, $"{name}.conf");
        var body = $$"""
        # BHServe site: {{name}}  ({{domain}})  php={{phpKey}} server=nginx
        server {
        {{ListenBlock(domain, cfg)}}
            server_name {{domain}};
            root {{Fwd(root)}};
            index index.php index.html index.htm;

            access_log {{home}}/logs/{{name}}-access.log;
            error_log  {{home}}/logs/{{name}}-error.log;

            location / { try_files $uri $uri/ /index.php?$query_string; }

            location ~ \.php$ {
                try_files $uri =404;
                include {{FastcgiParams}};
                fastcgi_pass 127.0.0.1:{{port}};
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
            }

            location ~ /\.(?!well-known).* { deny all; }
        }

        """;
        Directory.CreateDirectory(Paths.NginxSites);
        File.WriteAllText(conf, body);
    }

    /// <summary>Front a local HTTP service (e.g. Mailpit :8025) at a *.tld host (render_nginx_proxy_site analog).</summary>
    public static void RenderProxyVhost(string name, string domain, int port, Config cfg)
    {
        var conf = Path.Combine(Paths.NginxSites, $"{name}.conf");
        var body = $$"""
        # BHServe site: {{name}}  ({{domain}})  php=- server=proxy -> 127.0.0.1:{{port}}
        server {
        {{ListenBlock(domain, cfg)}}
            server_name {{domain}};
            location / {
                proxy_pass http://127.0.0.1:{{port}};
                proxy_set_header Host $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 600;
            }
        }

        """;
        Directory.CreateDirectory(Paths.NginxSites);
        File.WriteAllText(conf, body);
    }
}
